### ISSUE TITLE
Help, please?

### ISSUE THREAD

**Issue by OctoTheBitch** [ivydrinkscoffee/Splatoon.Cheats#1]
When I run cemu and launch splatoon and the cheat gen, It doesn't show up in memory editor, I've tried  launching the cheat gen before cemu and both in admin mode

**Comment by JulyCrab** [comment]
Same,it does not work.

**Comment by skweed767** [comment]
I found a fix the reason why it doesn't work because there is a error in the file it doesn't have the equal sign after the word address

**Comment by skweed767** [comment]
[0005000010176a00.zip](https://github.com/ivydrinkscoffee/Splatoon.Cheats/files/9221676/0005000010176a00.zip)
here is the edited file if you are to lazy to change it (this is for the eu version of splatoon)

**Comment by JulyCrab** [comment]
Thanks skweed

**Comment by ivydrinkscoffee** [comment]
> [0005000010176a00.zip](https://github.com/ivydrinkscoffee/Splatoon.Cheats/files/9221676/0005000010176a00.zip) here is the edited file if you are to lazy to change it (this is for the eu version of splatoon)

Hi! I'm sorry for not resolving this issue before I kinda stopped coding and making projects/using Github. I've found the issue now and I'll change it myself and credit you for spotting it of course.
